### PR TITLE
Site overhaul

### PR DESCRIPTION
**Pull request by husseinalhammad**
This is a bigger PR than I like, but there are some multiple blockers and due to limited time I grouped them all together.

## This adds

- [x] Global site header (see #30)
- [x] A separate navigation control for docs sidebar on mobile
- [x] Unified width on homepage and doc pages (see #30)
- [x] List of featured articles on home page
- [x] Global footer (see #30)
- [x] Sponsors components
- [x] Contribution Guide page
- [x] Unified color scheme across homepage and docs (see #30)

## Other changes

- The homepage is redesigned to be less market-y
- Less focus on getting more members - direct to a contribution guide instead of an application form
- List both sponsors & partners

### CODE REVIEW

**Review by alicemeichi — COMMENTED** [review]
Wow, thank you so much for putting in all the work to create such a cohesive experience, @husseinalhammad! Couple of initial thoughts...

- Are we removing the RSS feed link intentionally?

- The dark mode theme doesn't seem to align with the light mode theme. Should we have @megbosh take a look at it?

- The new header logo at 120px width appears to have some legibility issues with the "Markup Consortium" section. Should we try to set it to 50px height (+ no defined width) like the original site instead?

- More of a philosophical question about how we're heading. Do we really want to bury the membership forms and not have any link to them on the frontpage at all? Is this something we should discuss this at the Member's meeting perhaps?

- A bit of a "nice to have", but is it possible to make the header nav sticky?

**Comment by husseinalhammad** [comment]
> Are we removing the RSS feed link intentionally?

We can add it back to the footer. 

> The dark mode theme doesn't seem to align with the light mode theme. Should we have @megbosh take a look at it?

Tried darker shades of green, but looked off. Happy for @megbosh to help with this.

> The new header logo at 120px width appears to have some legibility issues with the "Markup Consortium" section. Should we try to set it to 50px height (+ no defined width) like the original site instead?

Yeah can be done. Even at 45px height it looks readable to me (50px seems a tiny bit too large?)

> More of a philosophical question about how we're heading. Do we really want to bury the membership forms and not have any link to them on the frontpage at all? Is this something we should discuss this at the Member's meeting perhaps?

We initially needed people to join. We kept the barrier to join very low. And this approach succeeded in driving >70 members to  join (not counting people who raised their hands as supporters).

We no longer need quantity. We can focus on getting the most out of these 70 members during this phase. The number of contributing members (during meetings, in written discussions or by doing work) is a lot smaller than 70.

I think with the new approach we may get fewer applicants overall, but the percentage of new applicants who are genuinely interested in contributing (meetings, written discussions or work) would be higher - which is what we need after all.


> A bit of a "nice to have", but is it possible to make the header nav sticky?

Can do

**Review by alicemeichi — APPROVED** [review]

**Comment by M-J-Robbins** [comment]
Hi sorry for the delay, loving it. A few notes

* Aside menu in the docs section is removed at 50em, the mobile version is put in at 35em. In between those sizes I think it’s missing completely 
* Sponsor logos don’t looks quite right in darkmode, would be good to check with them if they are happy with these.
    * Not a blocker if the sponsors are ok with it.
    *  If needed as a temporary fix could we keep these in light mode? 
* I also think a larger logo would be good. Rough guessing, I'd say with the logo at 65px is about 14px font-size.  It maybe doesn't need to be that size, but one change we should make is to use relative units so it scales with the rest of the page. Maybe `height:3em` or around that.
* As well as changing the logo to relative units, could we also do the same for
  * Sponsor logos
  * light/dark control
  * Social icons

**Comment by husseinalhammad** [comment]
> Sponsor logos don’t looks quite right in darkmode

This was highly inspired by the Vue (https://vuejs.org/) and Vite (https://vitejs.dev/) sites, but I agree these look a bit off (it could be because I am using a darker background colour). Reverted to the light grey BG and coloured logos.

**Pull request merged**
